module.exports = {
  up: async (queryInterface, _Sequelize) => {
    await queryInterface.bulkInsert('history', [
      {
        date: '20210702',
        content: '커피',
        amount: -5400,
        category_id: 2,
        payment_id: 2,
        user_id: 1,
      },
      {
        date: '20210704',
        content: '체육관 수강 등록',
        amount: -125300,
        category_id: 5,
        payment_id: 2,
        user_id: 1,
      },
      {
        date: '20210704',
        content: '토마토 소스 오므라이스',
        amount: -6500,
        category_id: 2,
        payment_id: 2,
        user_id: 1,
      },
      {
        date: '20210704',
        content: '출력소(컬러인쇄)',
        amount: -200,
        category_id: 7,
        payment_id: 1,
        user_id: 1,
      },
      {
        date: '20210707',
        content: '영화 스트리밍',
        amount: -9900,
        category_id: 6,
        payment_id: 2,
        user_id: 1,
      },
      {
        date: '20210707',
        content: '여름 의류',
        amount: -56000,
        category_id: 4,
        payment_id: 2,
        user_id: 1,
      },
      {
        date: '20210709',
        content: '7월 급여',
        amount: 1822480,
        category_id: 8,
        payment_id: 1,
        user_id: 1,
      },
      {
        date: '20210709',
        content: '잔치국수와 김밥',
        amount: -9500,
        category_id: 2,
        payment_id: 2,
        user_id: 1,
      },
      {
        date: '20210710',
        content: '7월 월세',
        amount: -500000,
        category_id: 1,
        payment_id: 1,
        user_id: 1,
      },
      {
        date: '20210710',
        content: '두유 4개',
        amount: -19140,
        category_id: 2,
        payment_id: 2,
        user_id: 1,
      },
      {
        date: '20210713',
        content: '온라인 세미나 신청',
        amount: -10000,
        category_id: 7,
        payment_id: 2,
        user_id: 1,
      },
      {
        date: '20210715',
        content: '후불 교통비 결제',
        amount: -45340,
        category_id: 3,
        payment_id: 2,
        user_id: 1,
      },
      {
        date: '20210715',
        content: '스트리밍서비스 정기 결제',
        amount: -10900,
        category_id: 6,
        payment_id: 2,
        user_id: 1,
      },
    ]);
  },

  down: async (queryInterface, _Sequelize) => {
    await queryInterface.bulkDelete('history', null, {});
  },
};
